name: PR Check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review

jobs:
  test-setting:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit 1

